// Apply the pattern-agents' review: drops, take fixes, counter-example flags, and the six answers.
import { readFile, writeFile } from 'node:fs/promises';
const doc = JSON.parse(await readFile('references.json', 'utf8'));
const DROP = ['mobbin:30fee836','mobbin:715206de','refero:20c8ba7c','mobbin:399ec1b5','mobbin:ee06623b','refero:9721','refero:4117','mobbin:733e9406','mobbin:a9dbeaf9'];
const TAKE = {
  'mobbin:b360aa69': 'Circle\'s create-event form opens under the global Events tab, not inside a course space: date/time, repeat rule and end date, with no course field.',
  'mobbin:d5d0e3c0': 'Repeats toggle → frequency → "Customize recurring event" (every / on / ends) → instances rendered on the calendar; no edit-scope dialog appears in the captured frames.',
  'refero:9872': 'Rescheduling one class instance opens a plain date/time panel with no "this / all" question: single-instance editing only.',
  'refero:023aed7b': 'Create/edit session modal has a "Resources: 1 rule" field but no availability or conflict feedback anywhere in the form.',
  'refero:9226': 'One-to-one lesson reschedule (list → menu → new slot) with nothing to link: no content selection, no group.',
  'refero:7186': 'Start time plus a duration dropdown (60 min); the time zone is only a read-only label, not a selector.',
};
const COUNTER = ['refero:9226','refero:9872','refero:023aed7b'];
const ANSWERS = {
Q1: 'Two surfaces coexist, and the strongest evidence shows them side by side in one product. Kajabi schedules sessions inline under a coaching product (mobbin:1680974d, flow mobbin:c497ddd0) and, separately, runs a Marketing → Events calendar with no product link at all (mobbin:64f56885). Luma is the global-with-tag model: the create form starts with "Create under [calendar]", so the container is chosen at creation (refero:1843). Acuity splits the reusable class type from the act of offering an instance on a date (refero:9859). Calendly (refero:df769788) and TravelPerk (refero:5222) are global-only lists with one Create button. Circle is the cautionary case: it has course spaces, yet its create-event form sits under the global Events tab (mobbin:b360aa69), and its "scheduled" course space flow is lesson drip, not bookable sessions (mobbin:f92f2d5a). For an instructor building a course calendar the inline surface wins because the course is implied context; the global calendar should be a filtered view with the course as tag. No reference shows the reverse direction (a course page listing events created from a global calendar), which is exactly the seam module 10 has to close.',
Q2: 'Only Understory shows an explicit content → event step: "+ Event" opens "Select the experience", and the form is then pre-filled with capacity, location, resources, rooms and guides (refero:12719). Workable gets the same effect by opening the event from the record, so the title and context are pre-populated (mobbin:da2ca788). HubSpot is the one product that treats the group as an object: the event side panel has "Associated campaign" and "Lists" sections, though both are empty in the capture (mobbin:0135db7d). Luma (mobbin:787e8052) and Rise (mobbin:1caacacf) link the event to individual attendees, with statuses, not to a cohort. Nothing in the set shows the link from the other side (a scenario or group page listing its sessions), and nothing attaches a learner group as a unit. Preply is the counter-example: a one-to-one lesson with nothing to link (refero:9226). For Essentials the event form should start from the scenario, as Understory does, accept learner groups as objects, as HubSpot lists do, and both the scenario and the group should list their sessions, which has to be designed without a reference.',
Q3: 'Recurrence at creation is table stakes: a repeat rule with frequency, weekdays and an end condition appears in Zoom (mobbin:b85c076b), Understory (refero:12705), Amie (mobbin:68dd9778) and Skiff, whose flow shows the customise modal and the instances rendered on the calendar (mobbin:d5d0e3c0). Edit scope is thinner than expected: Amie (mobbin:1c7e609d) and Motion (mobbin:1eb73c81) both ask "this event / all events", and no reference in this set offers the three-way "this and following". Luma is the only product that builds a series from an existing single event: "Create multi-session event" → add recurring sessions (cadence, number of weeks, weekday chips) or a manual session list → the event shows "+9 sessions" (refero:1848). Acuity is the counter-example: rescheduling one class instance shows a plain date/time panel with no scope question (refero:9872). Simulation sessions rarely repeat identically because groups rotate through scenarios, so Luma\'s explicit session list is a better fit than a bare repeat rule; the two-option scope dialog is still needed when a whole series moves.',
Q4: 'Every conflict message found is a soft warning shown after the fact, never a block inside the creation form. Acuity reopens a class with a yellow banner naming the resource ("uses resource Room #5") and still saves (refero:9868). Fresha warns that the staff member is not working at that time with Apply still enabled (mobbin:ac5e971e). Clockwise says "I can schedule this meeting, but there is a conflict for Sam" (mobbin:671e0870). 7shifts batches the check at publish time, counting conflicts and offering "fix them for me" (mobbin:8796902e). Google Workspace has a room and equipment picker with capacity but no availability feedback (mobbin:0a1650e1); SavvyCal\'s "Ignore calendar conflicts" toggle implies detection exists elsewhere (mobbin:44fd56e6); Zoom only complains at join time (mobbin:2ef394f0). Understory models resources with quantities (refero:12709) yet its session modal shows no conflict feedback at all (refero:023aed7b), the counter-example. No product shows equipment-specific conflicts. For a simulation centre, rooms, manikins and facilitators are the scarce resources, so the pattern to adopt is warn-don\'t-block, but moved into the form as live per-resource availability, which no reference demonstrates.',
Q5: 'Three sign-up models appear. Self sign-up: Aboard\'s single Attend toggle (mobbin:4fa0df58) and Partiful\'s RSVP with plus-one, where spots decrement per person, 20/20 to 18/20 (refero:10204). Approval-gated: Luma\'s guest list moves people from Pending approval to Going under a cap of 1,000 (mobbin:68dc9ea7). Host-added: SavvyCal lets the organiser invite a guest after scheduling (refero:3371). Capacity is a numeric field with a "no limit" option in Understory (refero:12706) and per ticket tier plus an event total in Eventbrite (mobbin:c0b0ead0). Attendance is always marked by the host: Posh toggles a guest to Checked in (mobbin:4022cce6); Lyssna offers Mark as completed / No-show and auto-completes after five days (mobbin:8a3407fe). No reference shows a waitlist or attendee self check-in. In Essentials attendance is mostly assigned through the learner group, so the useful borrowings are the capacity field with a no-limit option, Posh\'s check-in and Lyssna\'s automatic resolution of unmarked sessions.',
Q6: 'An explicit time-zone selector is the norm. Microsoft Teams leads the form with the zone, then start and end with a computed duration and an all-day toggle (refero:9746). Cal.com shows the zone on both the availability page and the booking page (mobbin:8a0d881c, refero:3492). Kajabi (mobbin:5de887fe), SavvyCal (mobbin:9a8fc4f4) and Clockwise (mobbin:1fe20459) pair the zone with duration presets and an availability grid. Zoom is the exception on duration, taking free hours and minutes (mobbin:f6032c78). Homerun uses start plus a duration dropdown and shows the zone only as a read-only label (refero:7186), the counter-example to the explicit selector. Upwork is the only product that previews the other party\'s local time ("2:16 PM GMT+8, 2h ahead") (mobbin:55d0a62f). Simulation sessions happen in a physical centre, so one institutional zone shown as a label is enough, and duration should default from the scenario\'s running time (module 05), which makes Homerun\'s start-plus-duration model the closest fit.',
};
const before = doc.references.length;
doc.references = doc.references.filter(r => !DROP.some(d => r.id.startsWith(d)));
for (const r of doc.references) {
  for (const [k, v] of Object.entries(TAKE)) if (r.id.startsWith(k)) r.take = v;
  r.counter_example = COUNTER.some(c => r.id.startsWith(c));
  r.selected = false;
}
for (const q of doc.questions) q.answer = ANSWERS[q.id] || '';
await writeFile('references.json', JSON.stringify(doc, null, 2) + '\n');
const apps = new Set(doc.references.map(r => r.app));
console.log(`refs ${before} → ${doc.references.length}; products ${apps.size}; counter ${doc.references.filter(r=>r.counter_example).length}`);
console.log([...apps].sort().join(', '));
// verify every id cited in answers exists
const ids = doc.references.map(r => r.id);
for (const [q, a] of Object.entries(ANSWERS)) for (const m of a.matchAll(/(mobbin|refero):[0-9a-f]+/g)) if (!ids.some(i => i.startsWith(m[0]))) console.log('MISSING cite', q, m[0]);
