// Generate only the new read-only 08 audit. No Figma calls or changes to other batches.
import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import vm from 'node:vm';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const p=JSON.parse(await fs.readFile(path.join(root,'board-plan.json'),'utf8'));
const expected={sections:p.sections.map(s=>({id:s.id,title:s.title})),rows:p.rows.map(r=>({id:r.id,question:r.question,url:r.url,source:r.source,total:r.totalImages,sequenceNote:r.sequenceNote,reportPathLabel:r.reportPathLabel,omitted:r.omittedStepIndices,images:r.images.map(i=>({i:i.i,x:i.x,label:i.label}))}))};
const code=`const FILE_KEY='tN2AM7RZD2InF1LYnN0zcn',PAGE_ID='5:422',PREFIX='UIID/2026-09-08/';
if(figma.fileKey&&figma.fileKey!==FILE_KEY)throw new Error('Wrong file');if(figma.editorType!=='figjam')throw new Error('Expected FigJam');
const page=await figma.getNodeByIdAsync(PAGE_ID);if(!page||page.type!=='PAGE')throw new Error('Required Page2 missing');await figma.setCurrentPageAsync(page);
const expected=${JSON.stringify(expected)},issues=[],sections=[],rowBounds=[],omissionChecks=[];
const nodes=page.findAll(n=>n.name.startsWith(PREFIX)),byName=new Map();for(const n of nodes){const a=byName.get(n.name)||[];a.push(n);byName.set(n.name,a);}
function one(name,type){const a=byName.get(name)||[];if(a.length!==1){issues.push('Expected one '+name+'; found '+a.length);return null;}if(type&&a[0].type!==type)issues.push('Unexpected node type '+a[0].id);return a[0];}
function bounds(n){return {id:n.id,x:n.x,y:n.y,w:n.width,h:n.height};}
function overlap(a,b){return a.x<b.x+b.w-1&&b.x<a.x+a.w-1&&a.y<b.y+b.h-1&&b.y<a.y+a.h-1;}
function inBounds(n,s){return n.x>=-1&&n.y>=-1&&n.x+n.width<=s.width+1&&n.y+n.height<=s.height+1;}
const sectionMap=new Map();for(const q of expected.sections){const label=q.id+' · '+q.title;const matches=page.children.filter(n=>n.type==='SECTION'&&(n.name===label||n.name===PREFIX+'section/'+q.id||n.children.some(c=>c.name===PREFIX+q.id+'/heading')));if(matches.length!==1){issues.push('Section count '+q.id+': '+matches.length);continue;}const s=matches[0];if(s.name!==label)issues.push('Nonhuman section name '+s.id);sectionMap.set(q.id,s);sections.push({question:q.id,...bounds(s)});for(const n of s.children)if(n.name.startsWith(PREFIX)&&!inBounds(n,s))issues.push('Outside section '+s.id+': '+n.id);}
const overviewMatches=page.children.filter(n=>n.type==='SECTION'&&(n.name==='University identity · Overview'||n.name===PREFIX+'introduction'||n.children.some(c=>c.name===PREFIX+'intro/title')));let overview=null;if(overviewMatches.length!==1)issues.push('Overview count '+overviewMatches.length);else{const n=overviewMatches[0];overview=bounds(n);if(n.name!=='University identity · Overview')issues.push('Nonhuman overview name');for(const c of n.children)if(c.name.startsWith(PREFIX)&&!inBounds(c,n))issues.push('Outside overview '+c.id);}
for(let i=0;i<sections.length;i++){for(let j=i+1;j<sections.length;j++)if(overlap(sections[i],sections[j]))issues.push('Section overlap '+sections[i].question+'/'+sections[j].question);if(overview&&overlap(sections[i],overview))issues.push('Overview overlaps '+sections[i].question);}
let references=0,sourceLinks=0,imageTargets=0,orderedRows=0;const ids=new Set(expected.rows.map(r=>r.id));
for(const n of nodes.filter(n=>n.name.startsWith(PREFIX+'reference/'))){const id=n.name.slice((PREFIX+'reference/').length).split('/')[0];if(!ids.has(id))issues.push('Unexpected reference node '+n.id+' '+id);}
for(const r of expected.rows){const key=PREFIX+'reference/'+r.id,sec=sectionMap.get(r.question);const sticky=one(key+'/sticky','STICKY'),source=one(key+'/source','TEXT'),context=one(key+'/context','TEXT'),report=one(key+'/report','TEXT');if(sticky&&source&&context&&report)references++;
 if(source){const link=source.getRangeHyperlink(0,source.characters.length);if(link&&link!==figma.mixed&&link.type==='URL'&&link.value===r.url)sourceLinks++;else issues.push('Incorrect source hyperlink '+r.id);}
 const owned=nodes.filter(n=>n.name.startsWith(key+'/'));if(sec&&owned.length){for(const n of owned)if(n.parent?.id!==sec.id)issues.push('Reference node in wrong section '+n.id);const minX=Math.min(...owned.map(n=>n.x)),minY=Math.min(...owned.map(n=>n.y)),maxX=Math.max(...owned.map(n=>n.x+n.width)),maxY=Math.max(...owned.map(n=>n.y+n.height));rowBounds.push({id:r.id,question:r.question,x:minX,y:minY,w:maxX-minX,h:maxY-minY});}
 let prevX=-Infinity,ordered=true;for(const im of r.images){const n=one(key+'/image/'+im.i,'SHAPE_WITH_TEXT'),caption=one(key+'/caption/'+im.i,'TEXT');if(n){imageTargets++;if(Math.abs(n.x-im.x)>1||n.x<=prevX){issues.push('Image order/x mismatch '+r.id+'#'+im.i);ordered=false;}prevX=n.x;}else ordered=false;
 const expectedCaption=(r.source==='documentation'?'Illustration ':'Step ')+(im.i+1)+' of '+r.total+' · '+im.label;if(caption&&caption.characters!==expectedCaption)issues.push('Caption/order mismatch '+r.id+'#'+im.i);}
 if(ordered)orderedRows++;
 if(report&&(!report.characters.includes(r.sequenceNote)||!report.characters.includes(r.reportPathLabel)))issues.push('Missing sequence/report pointer '+r.id);
 if(r.omitted.length){const ok=!!report&&report.characters.includes(r.sequenceNote);omissionChecks.push({id:r.id,omittedOriginalIndices:r.omitted,explicitNotePresent:ok});if(!ok)issues.push('Missing omissions '+r.id);}
}
for(const q of expected.sections){const rows=rowBounds.filter(r=>r.question===q.id);for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++)if(overlap(rows[i],rows[j]))issues.push('Row overlap '+rows[i].id+'/'+rows[j].id);for(let i=1;i<rows.length;i++)if(rows[i].y<=rows[i-1].y)issues.push('Reference order mismatch '+rows[i].id);}
const ownedStickyCount=nodes.filter(n=>n.name.startsWith(PREFIX+'reference/')&&n.name.endsWith('/sticky')).length;const ownedImageCount=nodes.filter(n=>n.name.startsWith(PREFIX+'reference/')&&/\\/image\\/\\d+$/.test(n.name)).length;
if(ownedStickyCount!==expected.rows.length)issues.push('Owned reference count mismatch '+ownedStickyCount);if(ownedImageCount!==expected.rows.reduce((n,r)=>n+r.images.length,0))issues.push('Owned image target count mismatch '+ownedImageCount);
return {fileKey:FILE_KEY,pageId:page.id,mutations:0,counts:{sections:sections.length,overviews:overview?1:0,references,sourceLinks,imageTargets,orderedRows,ownedStickyCount,ownedImageCount},omissionChecks,sections:sections.map(s=>({question:s.question,nodeId:s.id})),overviewNodeId:overview?.id||null,issues,passed:issues.length===0};`;
if(code.length>49000)throw Error('Audit too large');new vm.Script('(async function(){'+code+'})');const out=path.join(root,'figjam/generated-compact/08-audit-layout');await fs.writeFile(out+'.js',code+'\n');await fs.writeFile(out+'.request.json',JSON.stringify({fileKey:'tN2AM7RZD2InF1LYnN0zcn',skillNames:'figma-use,figma-use-figjam',description:'Audit Page2 source links, row layout and full-image order without mutations',code},null,2)+'\n');console.log(JSON.stringify({codeCharacters:code.length,references:expected.rows.length,images:expected.rows.reduce((n,r)=>n+r.images.length,0),omissionReferences:expected.rows.filter(r=>r.omitted.length).length}));
