import json
from pathlib import Path

base=Path(__file__).parent
flows={r['id']:r for r in json.loads((base/'evidence/refero-flows.json').read_text())['records']}
screens={r['uuid']:r for r in json.loads((base/'evidence/refero-selected-screens.json').read_text())['records']}
specs=[
 dict(key='91dab9ae-9676-49b6-8b26-01dde539cb0e',question='Q1',title='Configure a named SAML connection',actor='University IT',evidenceType='direct pattern',take='Explain every identity-provider value at the configuration field. Keep sign-in setup distinct from user provisioning, and add an explicit test before enabling institutional access.',observed='The SAML form requires a recognizable configuration name, SSO URL and certificate fingerprint. Helper text identifies the assertion-consumer URL and where to obtain certificate data. Optional logout URL and IP ranges follow; Save and Cancel end the form.',adaptation='Give university IT provider-specific instructions beside each field and a recognizable connection name. A separate test and rollout preview would reduce uncertainty before institutional sign-in changes.',limitation='One unfilled setup screen only. No connection test, save result, provider validation, group scope or provisioning lifecycle is visible. The proposed test is an adaptation, not an observed Zendesk step.',local=['assets/zendesk-saml.jpg'],labels=['Create SAML configuration']),
 dict(key='4fc8ea47-ce2b-40b1-8817-71e138851fcc',question='Q1',title='Separate sign-in from user provisioning',actor='University IT',evidenceType='direct pattern',take='Place authentication and provisioning in separate admin areas, explaining that automated account creation and removal need their own setup and support route.',observed='Organization Login has separate Single sign-on, User provisioning and Domain control tabs. The provisioning tab explains SCIM and provisioning/deprovisioning, marks Enterprise availability and offers help-center and Contact us routes.',adaptation='Use distinct setup states for institutional sign-in and user lifecycle. Explain capabilities and prerequisites before requesting directory access, with a support path when integration needs IT involvement.',limitation='This is an informational enterprise entry screen, not a working connection wizard. It does not demonstrate SCIM setup, scope selection, synchronization or deactivation results.',local=['assets/calendly-provisioning.jpg'],labels=['User provisioning explanation and support entry']),
 dict(key=4649,question='Q2',title='SSO email discovery with an explicit failure',actor='Faculty / learner',evidenceType='analogy',take='Keep institutional sign-in recognizable and explain when an email cannot use it. Give a support route and return path without implying that authentication creates course access.',observed='From the marketing entry, the login modal offers a separate SSO link. The user enters a work email. The final screen says the email is not recognized for SSO and directs the person to their organization administrator; Back to Log in remains available.',adaptation='Offer a clear university sign-in route alongside a separate guest route, with institution-specific support guidance when identity discovery fails. Treat this failure differently from successful sign-in without LearningSpace access.',limitation='No identity-provider handoff, successful authentication, account creation, linking or course-access check is shown. Guest routing is a proposed adaptation. The first screen is a long marketing page retained only for complete sequence provenance.',figjamImageIndices=[1,2,3,4],labels=['Marketing entry (context)','Login options with SSO link','SSO work-email entry','Email entered','SSO email not recognized; contact organization administrator']),
 dict(key=1250,question='Q4',title='Deactivate access while explaining content consequences',actor='LearningSpace administrator',evidenceType='analogy',take='Before deactivation, separate access loss from historical-content consequences. State what remains available and confirm the person has left the active list.',observed='The Members list opens a member details panel with role, joined date, Active status and Deactivate. Confirmation explains lost workspace access, which shared content remains accessible, ownership constraints and reactivation billing. After confirmation, the active member count drops from two to one and an update toast appears.',adaptation='Preview the effect on access, teaching history and retained learning records before a local deactivation. Keep deactivation separate from course enrollment removal and permanent deletion, and identify the system that owns the action.',limitation='This is a local workspace action, not a directory-triggered departure. The flow does not show retained inactive rows, an actual reactivation, identity re-linking, synchronization or learning-record retention policy.',labels=['Active workspace members','Member details and Deactivate action','Deactivation consequences and confirmation','Active list updated']),
 dict(key=671,question='Q5',title='Repeat-import matching and an all-error result',actor='LearningSpace administrator',evidenceType='analogy',take='Explain how repeat imports match existing people; report created, updated and failed rows separately. A finished job can still have zero successful records.',observed='The CSV introduction states that matching user ID or email updates an existing person; otherwise it creates one. The flow maps CSV columns, previews mapped attributes, adds import tags and runs a background import. Its final screen shows 0 users created, 0 users updated and 9 invalid-email errors with row and column details.',adaptation='For a Canvas export or other institutional CSV, require an explicit stable-identifier matching policy, preview additions versus updates, and provide actionable per-row validation. Preserve job history so administrators can correct and repeat a snapshot import.',limitation='All nine rows fail in the observed run; this is not partial success. Successful duplicate resolution, recovery retry and a downloaded error report are not shown. The source metadata calls this a happy path, which the actual final screen contradicts. Email matching here is an analogy, not a recommended university identity key.',deduplication='Reuses page-1 Refero flow 671 for materially new questions: identity matching on repeat imports and recovery from an all-error result. Page 1 used the flow for bulk-user entry/discovery. The prior reference record is reused for the new question. Page-1 assets were missing; supported full images were retrieved in this research round and reused without another download during selection.',figjamImageIndices=[0,1,3,4,6,10,11,12],labels=['Choose CSV importer','Read update-versus-create rule and choose users','CSV selected for upload','Choose source email column','Confirm column mapping','Mapped identifier, email and name; optional date step','Review mapped data','Import tags','Choose tags','Tags selected','Tags saved; ready to import','Import processing and history route','Job finished: 0 created, 0 updated, 9 invalid-email errors']),
 dict(key=10795,question='Q5',title='Map columns with sample data and validation review',actor='LearningSpace administrator',evidenceType='analogy',take='Preview sample values while mapping each column, then review valid and invalid counts before importing. Completion must distinguish accepted upload from finished processing.',observed='Contacts offers Add via CSV. After upload, Map your columns shows source fields alongside a selected field’s sample values, an auto-map control and destination field choices. The review shows name and email each valid for 10/10 records and zero invalid columns. After Add Contacts, a toast says the file is uploaded and processing may take a few minutes.',adaptation='Let administrators map Canvas or generic institutional exports while viewing real sample values. Show required identifiers and validation before commit, then link the processing state to a durable results page.',limitation='This is CRM contact enrichment, not account provisioning. Mapping only names and email proves neither stable identity matching nor course access. The final screen confirms processing, not completed additions, updates or failures.',figjamImageIndices=[0,1,2,3,5,6,7,8],labels=['Contacts: Add via CSV','Upload CSV and read requirements','Map source columns with sample values','Choose destination field for name','Name mapped; incomplete-mapping warning','Choose destination field for email','Both columns mapped','Review mappings: 10/10 valid in both columns','Upload accepted; processing toast'])
]
refs=[]
for spec in specs:
 key=spec.pop('key');labels=spec.pop('labels');local=spec.pop('local',None)
 if isinstance(key,int):
  source=flows[key]; steps=source['steps']; kind='flow'; app=source['site']['name']; urls=[s['thumbnail_url'] for s in steps]; ids=[s['screen_id'] for s in steps]
  local=[f'assets/refero-{key}/{i}.jpg' for i in range(len(steps))]
 else:
  source=screens[key];kind='screen';app=source['site']['name'];urls=[source['thumbnail_url']];ids=[key]
 assert len(labels)==len(local)==len(urls)
 ref=dict(id=f'refero:{key}',source='refero',app=app,kind=kind,url=source['refero_url'],images=urls,sourceIds=ids,source_ids=ids,accessedAt='2026-09-08',access_date='2026-09-08',selected=False,counter_example=False,localAssets=local,**spec)
 ref['evidence_type']=ref['evidenceType']
 if 'deduplication' in ref: ref['reuseRationale']=ref['deduplication']
 ref['boardStepIndices']=ref.get('figjamImageIndices',list(range(len(urls))))
 if len(ref['boardStepIndices'])<len(urls):
  ref['boardOmissionNote']='Selected original steps shown in order; omitted intermediate screens remain in the complete HTML report. Riverside omits the marketing entry; Intercom and Rox omit repetitive intermediate mapping/tag states.'
 ref['steps']=[dict(id=sid,label=label,index=i,imageIndex=i,localAsset=local[i],url=f'https://refero.design/pages/{sid}') for i,(sid,label) in enumerate(zip(ids,labels))]
 ref['assetProvenance']='Actual screenshot data retrieved through the supported Refero get_screen_image route with image_size=full; ordered original thumbnail URLs retained as source record metadata. JPEG local assets are used for report and board.'
 assert len(ref['take'].split())<=35,(ref['id'],len(ref['take'].split()))
 assert all((base/p).is_file() for p in local)
 refs.append(ref)
(base/'library-references.json').write_text(json.dumps({'module':'university-identity','title':'University identity, directory sync & user import','references':refs},indent=2)+'\n')
(base/'library-assets.json').write_text(json.dumps({r['id']:[str(Path(p).relative_to('assets')) for p in r['localAssets']] for r in refs},indent=2)+'\n')
print(f'{len(refs)} references; {sum(len(r["images"]) for r in refs)} local screenshots')
