const {chromium}=require('/Users/danielbrassnyo/.npm/_npx/9833c18b2d85bc59/node_modules/playwright');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.resolve(__dirname,'../01-objectives-outcomes-requirements.html'));
 await page.locator('.card img').evaluateAll(async imgs=>{await Promise.all(imgs.map(img=>{img.loading='eager';return img.decode().catch(()=>{});}));});
 const result=await page.evaluate(()=>({title:document.title,h2:[...document.querySelectorAll('h2')].map(x=>x.textContent),cards:document.querySelectorAll('.card').length,images:document.querySelectorAll('.card img').length,broken:[...document.querySelectorAll('.card img')].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.alt),externalImages:[...document.querySelectorAll('.card img')].filter(i=>!i.src.startsWith('data:')).length,synthesis:!!document.querySelector('#synthesis'),comparisonRows:document.querySelectorAll('tbody tr').length,invalidAnchors:[...document.querySelectorAll('a[href^="#"]')].filter(a=>!document.getElementById(a.getAttribute('href').slice(1))).map(a=>a.getAttribute('href')),overflow:document.documentElement.scrollWidth>innerWidth,status:document.querySelector('#status').textContent}));
 await page.screenshot({path:path.join(__dirname,'notes/qa-desktop.png')});
 await page.locator('.preview').first().click();
 result.lightbox=await page.locator('dialog').evaluate(d=>d.open);
 await page.locator('#close-lightbox').click();
 await page.locator('#search').fill('unlikely-qa-no-match');
 result.search=await page.locator('#status').innerText();
 await page.getByRole('button',{name:'Reset filters'}).click();
 await page.waitForFunction(()=>document.querySelector('#search').value==='');
 await page.locator('#selected').check();result.selectedStatus=await page.locator('#status').innerText();
 await page.locator('#selected').uncheck();
 await page.setViewportSize({width:390,height:844});
 result.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 await page.screenshot({path:path.join(__dirname,'notes/qa-mobile.png')});
 await page.locator('.question-section').first().scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(__dirname,'notes/qa-cards.png')});
 result.errors=errors;
 fs.writeFileSync(path.join(__dirname,'notes/qa.json'),JSON.stringify(result,null,2)+'\n');
 console.log(JSON.stringify(result));
 await browser.close();
 if(result.h2.length!==6||result.broken.length||result.externalImages||!result.synthesis||result.invalidAnchors.length||!result.lightbox||result.overflow||result.mobileOverflow||errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
