import { chromium } from '/Users/danielbrassnyo/.npm/_npx/9833c18b2d85bc59/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
const report = new URL('../04-learner-groups.html', import.meta.url);
const browser = await chromium.launch({headless:true,channel:"chrome"});
const page = await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
await page.goto(report.href);
await page.locator('.preview img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));
await page.waitForFunction(()=>[...document.querySelectorAll('.preview img')].every(i=>i.complete));
const result=await page.evaluate(()=>({h2:[...document.querySelectorAll('h2')].map(x=>x.textContent),cards:document.querySelectorAll('.card').length,images:document.querySelectorAll('.preview img').length,broken:[...document.querySelectorAll('.preview img')].filter(i=>!i.naturalWidth).map(i=>i.alt),externalImages:[...document.querySelectorAll('.preview img')].filter(i=>!i.src.startsWith('data:')).length,synthesis:!!document.querySelector('#synthesis'),badAnchors:[...document.querySelectorAll('#synthesis a[href^="#"]')].filter(a=>!document.getElementById(a.getAttribute('href').slice(1))).map(a=>a.getAttribute('href')),overflow:document.documentElement.scrollWidth>innerWidth}));
await page.screenshot({path:new URL('qa-desktop.png',import.meta.url).pathname});
await page.locator('.preview').first().click();
result.lightbox=await page.locator('#lightbox').evaluate(x=>x.open);
await page.locator('#close-lightbox').click();
await page.locator('#search').fill('no-matching-product-xyz');
result.search=await page.locator('#no-results').isVisible();
await page.locator('button[type=reset]').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:new URL('qa-mobile.png',import.meta.url).pathname});
result.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
result.errors=errors;
result.bytes=(await fs.stat(report)).size;
await fs.writeFile(new URL('qa.json',import.meta.url),JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
await browser.close();
if(result.h2.length!==6||result.broken.length||result.externalImages||!result.synthesis||result.badAnchors.length||errors.length||!result.lightbox||!result.search||result.overflow||result.mobileOverflow)process.exitCode=1;
