const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('/Users/danielbrassnyo/.npm/_npx/9833c18b2d85bc59/node_modules/playwright');
(async () => {
 const root=path.resolve(__dirname,'../..');
 const out=path.join(root,'.context/skills-competencies-qa');
 const report=path.join(root,'courses/03-skills-competencies.html');
 const doc=JSON.parse(fs.readFileSync(path.join(__dirname,'references.json'),'utf8'));
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+report);
 await page.locator('.preview img').evaluateAll(async imgs=>{await Promise.all(imgs.map(img=>{img.loading='eager';return img.decode()}))});
 const checks=await page.evaluate(()=>({h2:[...document.querySelectorAll('h2')].map(e=>e.textContent),cards:document.querySelectorAll('.card').length,images:[...document.querySelectorAll('.preview img')].map(i=>({ok:i.complete&&i.naturalWidth>0,embedded:i.src.startsWith('data:')})),synthesis:!!document.querySelector('#synthesis'),overflow:document.documentElement.scrollWidth>innerWidth}));
 if(checks.h2.length!==6 || checks.cards!==doc.references.length || checks.images.some(i=>!i.ok||!i.embedded)||!checks.synthesis||checks.overflow) throw Error(JSON.stringify(checks));
 await page.screenshot({path:path.join(out,'desktop.png')});
 await page.locator('.question-section').first().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'references.png')});
 await page.locator('.preview').first().click();if(!await page.locator('#lightbox').isVisible())throw Error('Lightbox failed');await page.locator('#close-lightbox').click();
 await page.locator('#search').fill('zzzz-no-match');if(await page.locator('.card:visible').count()!==0)throw Error('Search failed');
 await page.locator('button[type=reset]').click();await page.waitForTimeout(100);
 await page.locator('#selected').check();if(await page.locator('.card:visible').count()!==0)throw Error('Selected flag failed');
 await page.locator('button[type=reset]').click();await page.waitForTimeout(100);
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'mobile.png')});
 const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(mobileOverflow||errors.length)throw Error(JSON.stringify({mobileOverflow,errors}));
 fs.writeFileSync(path.join(out,'qa.json'),JSON.stringify({...checks,images:checks.images.length,mobileOverflow,errors,bytes:fs.statSync(report).size},null,2));
 console.log(JSON.stringify({cards:checks.cards,images:checks.images.length,h2:checks.h2.length,mobileOverflow,errors,bytes:fs.statSync(report).size}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
