import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const mod=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(mod,'../..');
const pipe=path.join(root,'userflow-patterns--user-mgmt/inspiration/scripts');
const report=path.join(root,'courses/07-share-with-participants.html');
const refs=JSON.parse(await fs.readFile(path.join(mod,'references.json'),'utf8'));
execFileSync('node',[path.join(pipe,'build-report.mjs'),path.join(mod,'references.json'),'--embed','--assets',path.join(mod,'assets/manifest.json'),'--out',report],{stdio:'inherit'});
let html=await fs.readFile(report,'utf8');
let index=0;
html=html.replace(/<article class="card"/g,match=>`${match} id="ref-${encodeURIComponent(refs.references[index++].id)}"`);
index=0;
html=html.replace(/<div class="card-body">/g,match=>`${match}<small class="muted">${refs.references[index++].id}</small>`);
const synthesis=await fs.readFile(path.join(mod,'synthesis.html'),'utf8');
html=html.replace('</header>','</header>\n'+synthesis);
await fs.writeFile(report,html);
console.log('Synthesis inserted; stable reference anchors added.');
