const { chromium } = require('/Users/danielbrassnyo/.npm/_npx/9833c18b2d85bc59/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
 const dir=__dirname;
 const report=path.resolve(dir,'../07-share-with-participants.html');
 const browser=await chromium.launch({headless:true,executablePath:"/Users/danielbrassnyo/Library/Caches/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-mac-arm64/chrome-headless-shell"});
 const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+report);
 await page.locator('.card img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));
 await page.waitForFunction(()=>[...document.querySelectorAll('.card img')].every(i=>i.complete));
 const result=await page.evaluate(()=>({headings:[...document.querySelectorAll('h2')].map(e=>e.textContent),cards:document.querySelectorAll('.card').length,images:document.querySelectorAll('.card img').length,broken:[...document.querySelectorAll('.card img')].filter(i=>!i.naturalWidth).map(i=>i.alt),externalImages:[...document.querySelectorAll('.card img')].filter(i=>!i.src.startsWith('data:')).length,synthesis:!!document.querySelector('#synthesis'),overflow:document.documentElement.scrollWidth>innerWidth}));
 await page.screenshot({path:path.join(dir,'qa-desktop.png')});
 await page.locator('.preview').first().click();
 result.lightbox=await page.locator('#lightbox').evaluate(x=>x.open);
 await page.locator('#close-lightbox').click();
 await page.locator('#search').fill('unlikely-no-match-qa');
 result.searchWorks=await page.locator('#no-results').isVisible();
 await page.locator('button[type=reset]').click();
 await page.locator('.question-section').first().scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(dir,'qa-reference-section.png')});
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(dir,'qa-mobile.png')});
 result.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 result.errors=errors;result.bytes=fs.statSync(report).size;
 fs.writeFileSync(path.join(dir,'qa.json'),JSON.stringify(result,null,2));
 console.log(JSON.stringify(result,null,2));await browser.close();
 if(result.headings.length!==6||result.broken.length||result.externalImages||!result.synthesis||errors.length||result.overflow||result.mobileOverflow)process.exitCode=1;
})();
